export const OPEN_LOGIN_LAYER = 'OPEN_LOGIN_LAYER';

export const CLOSE_LOGIN_LAYER = 'CLOSE_LOGIN_LAYER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SIGN_IN_WITH_MAIL = 'SIGN_IN_WITH_MAIL';

export const CANCEL_MAIL_SIGN_IN = 'CANCEL_MAIL_SIGN_IN';

export const EMAIL_IN_USE_BY_PROVIDER = 'EMAIL_IN_USE_BY_PROVIDER';

export const EMAIL_USER_EXISTS = 'EMAIL_USER_EXISTS';

export const RESET_LOGIN_LAYER = 'RESET_LOGIN_LAYER';

export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILURE =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILURE';

export const CLEAR_ALL_FORM_ERRORS = 'CLEAR_ALL_FORM_ERRORS';

export const EMAIL_AVAILABLE_TO_CREATE = 'EMAIL_AVAILABLE_TO_CREATE';

export const CLEAR_FORM_ERROR = 'CLEAR_FORM_ERROR';

export const SET_PERFORMING_ASYNC = 'SET_PERFORMING_ASYNC';

export const UNSET_PERFORMING_ASYNC = 'UNSET_PERFORMING_ASYNC';
